### PR TITLE
Update to libc 0.2.30 for emscripten support

### PR DESCRIPTION
**Pull request by lilianmoraru**

### CODE REVIEW

**Comment by lilianmoraru** [comment]
For some reason fails at this assert: https://github.com/danburkert/fs2-rs/blob/82639f32ae26e7bc7fecc588a37cbd4fe68ef1e8/src/lib.rs#L325

Curious if it is a test stability problem or in some version of `libc` something changed(I observed that the tests that passed use an old version of `libc`, so other versions might of changed the situation too).

**Comment by lilianmoraru** [comment]
Probably flaky? It ran ok in my case: https://travis-ci.org/lilianmoraru/fs2-rs/builds/268981651

**Comment by lilianmoraru** [comment]
Side note, the failing test ran on [precise](https://travis-ci.org/danburkert/fs2-rs/jobs/268974667/config), while my run was on the newer [trusty](https://travis-ci.org/lilianmoraru/fs2-rs/jobs/268981661/config).

**Comment by danburkert** [comment]
Yep looks like a flake.  Thanks for the PR!  I imagine I should wait till resolution of #19 before cutting a release, right?  AFAIK just this change alone isn't worth releasing, since `cargo update` in downstream apps should have the same effect.

**Comment by lilianmoraru** [comment]
@danburkert Yes, https://github.com/rust-lang/rust/pull/44116 + #19 need to land first...

**Pull request merged**
