### PR TITLE
Add emscripten support

### PR DESCRIPTION
**Pull request by malbarbo**

### CODE REVIEW

**Comment by malbarbo** [comment]
Tests fails using node, it seems that libc is broken for emscripten, but `posix_fallocate` is [available]((https://github.com/kripken/emscripten/blob/master/system/lib/libc/musl/src/fcntl/posix_fallocate.c)) on emsdk musl.

I'm working in improving the emscripen in the rust ecosystem, could you please release a new dot release?

**Comment by malbarbo** [comment]
[PR](https://github.com/rust-lang/libc/pull/610) to enable and fixes tests for libc on emscripten.

**Comment by danburkert** [comment]
I'm not quite following, is this ready to merge?

**Comment by malbarbo** [comment]
I though before that this was ready to merge, but now I think we should wait until we can test this. After libc PR got merged, I will send a PR to update libc on rust, then we can run the tests and make sure it works.

**Comment by danburkert** [comment]
SGTM, thanks.

**Comment by lilianmoraru** [comment]
The new libc is getting merged upstream: https://github.com/rust-lang/rust/pull/44116

**Comment by danburkert** [comment]
Is there any way to add emscripten coverage to travis?

**Comment by lilianmoraru** [comment]
@malbarbo `libc 0.2.30` was merged in the `nightly` Rust.
With this fix, we could try to test on nightly(binaries through `rust-buildbot` probably not available yet).
I still think that a new version should not be published until Travis is set to test the target.

**Comment by danburkert** [comment]
Yah I agree, it would be nice to have emscripten coverage in CI if feasible.  However, If it would require jumping through a bunch of hoops, I could be convinced to go ahead since this is such a minimal change.

**Comment by danburkert** [comment]
Is this still a concern with all of the recent WASM stuff landing in Rust?  I admit I haven't been following that as closely as I might, since I don't target browsers.

**Comment by lilianmoraru** [comment]
Well, packages that depend on `fs2` will still not be able to compile because of that missing `cfg`.

**Comment by danburkert** [comment]
@lilianmoraru has anything changed WRT feasibility of testing with travis?

**Comment by lilianmoraru** [comment]
@danburkert
- [`cargo web test`](https://github.com/koute/cargo-web#features)
- [`wargo test`](https://github.com/lord/wargo)

**Comment by danburkert** [comment]
OK sounds good, let's leave this open then.  I'm not personally going to have time to drive it forward, but I welcome others to.

Thanks @lilianmoraru !

**Comment by lilianmoraru** [comment]
All the blockers have been closed(maybe a `libc` update would be good).
What do you think about getting this in and then somebody could work on the CI?

**Comment by danburkert** [comment]
Yeah I'm fine with that.  The libc version is floating (`^`), so I don't think it should cause problems.  I'll go ahead and merge.

**Pull request merged**
