### PR TITLE
Fix compilation on Solaris/Illumos

### PR DESCRIPTION
**Pull request by nbaksalyar**

### CODE REVIEW

**Comment by danburkert** [comment]
Hey, thanks for the PR!  It looks like Solaris [might have](https://docs.oracle.com/cd/E26502_01/html/E29034/posix-fallocate-3c.html) the `posix_fallocate` system call.  Did you try adding it to that impl instead of the no-op?

**Comment by danburkert** [comment]
I unfortunately do not have a solaris machine to test myself.

**Comment by nbaksalyar** [comment]
> Did you try adding it to that impl instead of the no-op?

I didn't go deep yet because failing compilation is a blocker for bringing Cargo to the platform, which is I'm currently focused on.

But it's worth to give it a full support, thanks for pointing this out!

**Comment by danburkert** [comment]
Yah it should be the same difficulty either way.  If it doesn't work I'll go ahead and merge it as is.

**Comment by nbaksalyar** [comment]
Well, it turns out that this function is supported only for certain file systems, and on the default (ZFS) it returns an EINVAL error, so the tests are failing. To quote a mailing list that I've googled:

> The issue was that posix_fallocate [...] always failed with EINVAL.  It turned out that Solaris has a strange (or rather, invalid) interpretation of the POSIX.1 spec [...] posix_fallocate resp. the underlying fcntl(F_ALLOCSP) is only supported on UFS, but there's no indication in the manpage about this.  This filesystem dependence makes the function pretty useless

https://sourceware.org/bugzilla/show_bug.cgi?id=12987

So I guess this can be merged as is.

**Comment by danburkert** [comment]
OK, thanks!

**Pull request merged**
